### ISSUE TITLE
crm_new_feature_small - AOL mail rendering

### ISSUE THREAD

**Issue by Karishma-Kothari** [Financial-Times/crm-meme-templates#22]
Just noticed that there is a blue box appearing around the image in the second version in AOL mail. 
![image](https://cloud.githubusercontent.com/assets/24919974/21650221/27395782-d29c-11e6-8056-2aebe7c3e427.png)

**Comment by Karishma-Kothari** [comment]
@jonomilnes

**Comment by jonomilnes** [comment]
@Karishma-Kothari now fixed:
https://litmus.com/checklist/emails/public/e76beed

Please check, and if happy close this issue :)

Thanks!

**Comment by Karishma-Kothari** [comment]
@jonomilnes Looks good but I've just noticed for Outlook the text styling for the heading is not appearing:
![image](https://cloud.githubusercontent.com/assets/24919974/21650917/7bed1b72-d29e-11e6-9ecb-c035e80bfbb6.png)

**Comment by jonomilnes** [comment]
@Karishma-Kothari fix now here:
https://litmus.com/checklist/emails/public/e76beed

thanks!

**Comment by Karishma-Kothari** [comment]
@jonomilnes GORGEOUS!

**Comment by jonomilnes** [comment]
closing this issues
