### ISSUE TITLE
Email 3 - Life and Arts DW - view in browser link

### ISSUE THREAD

**Issue by AislinnMcG** [Financial-Times/crm-meme-templates#41]
Not clickable in the welcome

@melanierogan @jonomilnes

**Comment by melanierogan** [comment]
This is now working:
http://email.permalink.ft.com/emails/eyJlbWFpbCI6ImY2ZDgxZTQxMTY4N2JjMjcwMzY2MmMyOGRjNWRjZjY0YWIxYWIzNmQiLCJ0cmFuc2FjdGlvbklkIjoiNDMwYmFlNDMtNmEyMi00Mjg1LTgwYjctMmE0N2E3NTJiMDcxIn0%3D
