### ISSUE TITLE
Welcome headlines section errors

### ISSUE THREAD

**Issue by AislinnMcG** [Financial-Times/crm-meme-templates#46]
Hi mel, 

I have been going through the welcome tests, and there are a few issues with the headlines content...

L&As email issue with the video image:
http://email.permalink.ft.com/emails/eyJlbWFpbCI6ImZhZDQwMTRjMTE4MGI3MjcxYzZhMmMzY2MwNzZlOTc2ZjE1N2JmNmY5ZSIsInRyYW5zYWN0aW9uSWQiOiIyMmUwYjJkYS01NGNhLTQwNWQtOTZkYS1lNjU2MDg1ZmY4MjYifQ%3D%3D

Email 2: no image pulling through:
http://email.permalink.ft.com/emails/eyJlbWFpbCI6ImZhZDQwMTRjMTE4MGI3MjcxYzZhMmMzY2MwNzZlOTc2ZjE1N2JmNmY5ZSIsInRyYW5zYWN0aW9uSWQiOiJiN2Y0YzhiYS04ZTE5LTRlMWEtODg5ZS03YmMzN2QxOWJjMDkifQ%3D%3D

Another example only one story:
http://email.permalink.ft.com/emails/eyJlbWFpbCI6ImZhZDQwMTRjMTE4MGI3MjcxYzZhMmMzY2MwNzZlOTc2ZjE1N2JmNmY5ZSIsInRyYW5zYWN0aW9uSWQiOiJkYWM1ZDliZi0wZWIyLTRkOWItOTk0Ni0yM2Q4ZTYyMzc3ZjIifQ%3D%3D

Email 1: only 2x stories for fast FT
http://email.permalink.ft.com/emails/eyJlbWFpbCI6ImZhZDQwMTRjMTE4MGI3MjcxYzZhMmMzY2MwNzZlOTc2ZjE1N2JmNmY5ZSIsInRyYW5zYWN0aW9uSWQiOiI0NjVkZDkzMy05ZWRjLTRjNzgtYTJhYS0zNDkyNWM5ZDc0MjQifQ%3D%3D

Email 9 world news, only one story:
http://email.permalink.ft.com/emails/eyJlbWFpbCI6ImZhZDQwMTRjMTE4MGI3MjcxYzZhMmMzY2MwNzZlOTc2ZjE1N2JmNmY5ZSIsInRyYW5zYWN0aW9uSWQiOiIxMGQwYzNmMy1jMDYxLTRjMWItYTQ2My1iYjA5NTJhNDFkZGUifQ%3D%3D

Also there are inconsistency in the arrow.....

![image](https://cloud.githubusercontent.com/assets/24526641/24099588/10191432-0d68-11e7-8bf7-de9bbe696c40.png)

![image](https://cloud.githubusercontent.com/assets/24526641/24099619/30da7058-0d68-11e7-82a4-78484683477a.png)

**Comment by melanierogan** [comment]
Added to tech debt
